[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "aiida-pl"
dynamic = ["version"]
description = ''
readme = "README.md"
requires-python = ">=3.9"
license = {file = "LICENSE"}
keywords = []
authors = []
classifiers = [
  "Development Status :: 4 - Beta",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3.9",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
]

[tool.hatch.version]
path = "src/aiida_pl/__about__.py"


[tool.hatch.envs.docs]
dependencies = [
  "mystmd"
]
scripts.build = "cd docs && myst build"
scripts.start = "cd docs && myst start"


[tool.hatch.envs.precommit]
dependencies = ["pre-commit"]
scripts.install = "pre-commit install"
scripts.run = "pre-commit run {args:--all-files}"
